/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class product_miyabi_android_leveldb_db_Database */

#ifndef _Included_product_miyabi_android_leveldb_db_Database
#define _Included_product_miyabi_android_leveldb_db_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     product_miyabi_android_leveldb_db_Database
 * Method:    VERSION
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_product_miyabi_android_leveldb_db_Database_VERSION
  (JNIEnv *, jclass);

/*
 * Class:     product_miyabi_android_leveldb_db_Database
 * Method:    OpenNative
 * Signature: (Lproduct/miyabi/android/leveldb/db/options/Options;Ljava/lang/String;)Lproduct/miyabi/android/leveldb/db/Status;
 */
JNIEXPORT jobject JNICALL Java_product_miyabi_android_leveldb_db_Database_OpenNative
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
