/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class product_miyabi_android_leveldb_db_Database */

#ifndef _Included_product_miyabi_android_leveldb_db_Database
#define _Included_product_miyabi_android_leveldb_db_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     product_miyabi_android_leveldb_db_Database
 * Method:    VERSION
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_product_miyabi_android_leveldb_db_Database_VERSION
  (JNIEnv *, jobject);

/*
 * Class:     product_miyabi_android_leveldb_db_Database
 * Method:    _open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_product_miyabi_android_leveldb_db_Database__1open
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
